### ISSUE TITLE
Fulfill the Inaka Open-Source Checklist

### ISSUE THREAD

**Issue by elbrujohalcon** [inaka/fiar#13]
From [Inaka's wiki](https://github.com/inaka/inaka_corp/wiki/Open-Source-checklist):
## General Items
- [x] It has a github repo
- [x] It has a proper LICENSE file
- [x] It's hooked to a hipchat room
- [x] It's has a clear and useful README.md
- [x] It's documented (with examples)
- [x] It's tested
## Exhibition
- [ ] There is a blog post about it
- [ ] It's shared on social networks
## For Erlang Projects
- [x] It's checked with [Elvis](http://github.com/inaka/elvis)
